name:                delaunay
version:             0.1.0.0
github:              "JohnL4/Delaunay"
license:             MIT
author:              "John Lusk"
maintainer:          "john-haskell-stack@how-hard-can-it-be.com"
copyright:           "2019 John Lusk"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Gives Delaunay triangulation of a set of 2-D points.
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JohnL4/Delaunay#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  delaunay-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delaunay

tests:
  delaunay-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - delaunay
    - hspec
